--- 
excluded_pkgfiles: 
- lib/redleaf/archetypes*
- spec/redleaf/archetypes*
project_requirements: 
  Redland: ">= 1.0.9"
project_pubdir: /usr/local/www/public/code
project_description: |-
  Redleaf is an RDF library for Ruby. It's composed of a hand-written binding 
  for the Redland RDF Library, and a high-level, more idiomatic Ruby layer.
project_pubhost: deveiate
project_homepage: http://deveiate.org/projects/Redleaf
release_mailto: Ruby-Talk List <ruby-talk@ruby-lang.org>
project_dependencies: {}

release_smtphost: mail.faeriemud.org
project_summary: An RDF library for Ruby
project_name: Redleaf
version_file: redleaf.rb
additional_pkgfiles: 
- spec/templates
- spec/spec_generator.rb
- examples/*.rb
dev_dependencies: 
  rubyzip: ">= 0.9.1"
authors: 
  Michael Granger: ged@FaerieMUD.org
post_install_message: |-
  Thanks for installing Redleaf!
  
  If you have questions, comments, suggestions or find a bug, please contact us via
  the bug-tracker on the project page:
  
    http://deveiate.org/projects/Redleaf
  
  Happy RDFing!
